dependencies:
  build:
    - ruby:2.6.0

build_targets:
  - name: default
    commands:
      - gem install bundler
      - bundle install
      - bundle rake rspec

ci:
  builds:
    - name: default
      build_target: default
